spring:
  datasource:
      #url: jdbc:postgresql://192.168.99.100:5444/cats-api #ip захардкожен, лучше использовать переменную окружения:
      url: jdbc:postgresql://${DATASOURCE_HOST}:5444/cats-api
      username: admin
      password: admin